<a href="https://colab.research.google.com/github/gaurav-0022/Assignment-1/blob/main/Copy_of_Pandas_Dataframe.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from google.colab import files
uploaded = files.upload()

Saving Retail_dataset.csv to Retail_dataset.csv

## Q1. Creating a DataFrame

In [ ]:
import pandas as pd

data = {
    "Product": ["A", "B", "C", "D", "E"],
    "Region": ["East", "West", "North", "South", "East"],
    "Sales": [1000, 1500, 2000, 1200, 1800],
    "Quantity": [10, 15, 20, 12, 18]
}

df1 = pd.DataFrame(data)
df1

  Product Region  Sales  Quantity
0       A   East   1000        10
1       B   West   1500        15
2       C  North   2000        20
3       D  South   1200        12
4       E   East   1800        18

##Load Dataset (for Q2–Q10)

In [ ]:
df = pd.read_csv("Retail_dataset.csv")
df.head()

   Order_ID Customer   Product Region  Sales  Quantity
0      1001    Sneha    Laptop   West   1056         2
1      1002     Neha    Tablet  South    904         7
2      1003    Meera    Laptop  South   1597         5
3      1004    Rohan  Keyboard  North    777         8
4      1005    Priya     Phone  South   2028         4

##Q2: Data Inspection

In [ ]:
# First 5 rows
df.head()

# Last 5 rows
df.tail()

# Dataset info
df.info()

# Shape
df.shape

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 90 entries, 0 to 89
Data columns (total 6 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Order_ID  90 non-null     int64
 1   Customer  90 non-null     object
 2   Product   90 non-null     object
 3   Region    90 non-null     object
 4   Sales     90 non-null     int64
 5   Quantity  90 non-null     int64
dtypes: int64(3), object(3)
memory usage: 4.3+ KB

(90, 6)

## Q3. Column Selection

In [ ]:
df[["Product", "Region", "Sales"]]

     Product Region  Sales
0     Laptop   West   1056
1     Tablet  South    904
2     Laptop  South   1597
3   Keyboard  North    777
4      Phone  South   2028
..       ...    ...    ...
85    Laptop   East   1330
86  Keyboard   West    741
87   Monitor   East    875
88    Tablet  North   2213
89    Laptop  South   1270

[90 rows x 3 columns]

## Q4. Indexing using .loc

In [ ]:
# Row with index 10
df.loc[10]

# Sales value at index 20
df.loc[20, "Sales"]

np.int64(1021)

## Q5. Indexing using .iloc

In [ ]:
# First 6 rows and first 4 columns
df.iloc[:6, :4]

# Sales value from 3rd row
df.iloc[2]["Sales"]

np.int64(1597)

## Q6. Row Slicing

In [ ]:
# First 10 rows
df.head(10)

# Rows 15 to 25
df.iloc[15:26]

    Order_ID Customer  Product Region  Sales  Quantity
15      1016    Karan  Monitor   West    796         3
16      1017     Neha   Laptop   East   2015         2
17      1018    Anita    Phone  North   1637         3
18      1019     Amit    Phone   East    748         7
19      1020     Neha   Laptop   West   1503         6
20      1021    Priya   Laptop  North   1021         4
21      1022      Raj   Tablet  South    886         7
22      1023    Rahul   Laptop  South   2267         3
23      1024    Karan  Monitor   East    814         7
24      1025    Meera  Monitor   West   1926         6
25      1026    Anita   Tablet   East    839         5

## Q7. Filtering Data

In [ ]:
# Region = East
df[df["Region"] == "East"]

# Sales > 1500
df[df["Sales"] > 1500]

    Order_ID Customer   Product Region  Sales  Quantity
2       1003    Meera    Laptop  South   1597         5
4       1005    Priya     Phone  South   2028         4
9       1010     Amit     Phone   West   1998         4
10      1011      Raj   Monitor  North   1693         6
13      1014    Rohan     Phone  South   2078         3
16      1017     Neha    Laptop   East   2015         2
17      1018    Anita     Phone  North   1637         3
19      1020     Neha    Laptop   West   1503         6
22      1023    Rahul    Laptop  South   2267         3
24      1025    Meera   Monitor   West   1926         6
26      1027    Vikas    Laptop  North   1864         8
27      1028    Vikas    Laptop  North   1551         3
29      1030    Rohan   Monitor   West   1932         5
31      1032     Amit    Laptop   East   2226         6
34      1035     Amit    Tablet   East   2104         3
35      1036    Rohan     Phone   East   2136         8
36      1037      Raj     Phone   East   1650         4
37      1038     Amit   Monitor   East   1567         8
38      1039    Meera  Keyboard   East   2455         3
42      1043    Meera  Keyboard   West   1515         6
43      1044    Vikas    Laptop   West   2248         5
44      1045    Priya     Phone   East   1875         4
49      1050    Karan   Monitor   West   2034         7
52      1053    Rahul    Laptop   East   2276         1
57      1058    Meera    Tablet  North   1666         8
58      1059    Karan    Tablet   West   2404         6
59      1060    Karan    Tablet   West   1651         2
60      1061    Vikas   Monitor  South   1837         8
61      1062    Meera  Keyboard  North   1688         4
63      1064    Pooja  Keyboard   West   2310         5
66      1067    Rahul    Tablet   East   1875         6
69      1070    Rahul    Tablet   West   2134         5
71      1072    Anita  Keyboard   East   1702         3
74      1075     Amit   Monitor  North   2390         5
79      1080    Pooja    Tablet   East   1829         2
81      1082    Anita     Phone   East   1695         7
82      1083     Neha  Keyboard   East   2034         5
88      1089      Raj    Tablet  North   2213         5

## Q8. Multiple Condition Filtering

In [ ]:
df[(df["Region"] == "West") & (df["Sales"] > 1200)]

    Order_ID Customer   Product Region  Sales  Quantity
9       1010     Amit     Phone   West   1998         4
19      1020     Neha    Laptop   West   1503         6
24      1025    Meera   Monitor   West   1926         6
29      1030    Rohan   Monitor   West   1932         5
42      1043    Meera  Keyboard   West   1515         6
43      1044    Vikas    Laptop   West   2248         5
49      1050    Karan   Monitor   West   2034         7
55      1056    Rahul    Laptop   West   1481         1
58      1059    Karan    Tablet   West   2404         6
59      1060    Karan    Tablet   West   1651         2
63      1064    Pooja  Keyboard   West   2310         5
68      1069    Priya    Laptop   West   1422         6
69      1070    Rahul    Tablet   West   2134         5
73      1074    Meera  Keyboard   West   1429         7
83      1084    Rohan    Laptop   West   1204         5
84      1085     Neha   Monitor   West   1339         7

## Q9. Descriptive Statistics

In [ ]:
stats = df.describe()
stats

# Extract values
mean_sales = stats.loc["mean", "Sales"]
max_quantity = stats.loc["max", "Quantity"]
min_sales = stats.loc["min", "Sales"]

print("Mean Sales:", mean_sales)
print("Max Quantity:", max_quantity)
print("Min Sales:", min_sales)

Mean Sales: 1406.888888888889
Max Quantity: 8.0
Min Sales: 515.0

## Q10. Aggregation Analysis

In [ ]:
total_sales = df["Sales"].sum()
avg_sales = df["Sales"].mean()
max_sales = df["Sales"].max()
min_sales = df["Sales"].min()

print("Total Sales:", total_sales)
print("Average Sales:", avg_sales)
print("Maximum Sales:", max_sales)
print("Minimum Sales:", min_sales)

Total Sales: 126620
Average Sales: 1406.888888888889
Maximum Sales: 2455
Minimum Sales: 515